mill: migrate bnfc module to use jflex+cup instead of antlr (#442)
JFlex and Java Cup will be needed to provide locations in the parsed BNFC AST classes.

This PR makes a few related changes:
- refactor BNFCModule to be independent of the parser compilation backend.
- add JFlexCupModule
- move all the helper .mill files into a basilmill subfolder



* starting jflex.

Exception in thread "Thread-0" java.lang.NoSuchMethodError: 'short[][] jflex.core.LexParse.unpackFromStrings(java.lang.String[])'

* it works????????

* touch

* show stdout

* refactor BNFCModule to be backend independent

* add bnfcBackendArg

* download cup sources to re-host javadocs

* move