ci: fix formatting job passing despite failures (#573)
fix issue with failing to handle BSTATE and ne_bits in dsa/correct/split/clang test case

re-lift dsa split test case to remove unhandled instructions from different arm version

ensure bap-normalise.py has LF line-endings to prevent issues when using lifting scripts

scalafmt

improve match in resolveFieldExpr

ci: scalatest.sh (#576)

follow up to https://github.com/UQ-PAC/BASIL/pull/569

this was missed in the first pr and can cause the same nondeterministic
failures...
```python
Mill daemon exited unexpectedly!
No daemon stdout

Daemon stderr:

Error: Exception in thread "main" java.lang.Exception: Mill server process already present
	at mill.server.Server.run$$anonfun$2(Server.scala:157)
	at mill.server.Server.run$$anonfun$adapted$1(Server.scala:157)
	at scala.Option.getOrElse(Option.scala:201)
	at mill.server.Server.run(Server.scala:157)
	at mill.daemon.MillDaemonMain$.main$$anonfun$1(MillDaemonMain.scala:45)
	at mill.daemon.MillDaemonMain$.main$$anonfun$adapted$1(MillDaemonMain.scala:49)
	at mill.api.SystemStreamsUtils$.withTopLevelSystemStreamProxy(SystemStreamsUtils.scala:74)
	at mill.daemon.MillDaemonMain$.main(MillDaemonMain.scala:49)
	at mill.daemon.MillDaemonMain.main(MillDaemonMain.scala)
unable to determine mill class output directory:
Error: Process completed with exit code 1.
```

Widen during function summary generation (#546)

Turns on the widening flag of the worklist solver when doing an interval
analysis so that things terminate

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

mill: scala 3.3.7 (#558)

this brings in my first scaladoc feature!
https://www.github.com/scala/scala3/pull/23676

scala discourse thread
https://contributors.scala-lang.org/t/scala-3-3-7-lts-release-thread/7228

"The final release is planned for 24th September 2025"

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

Replace irreducible loop analysis and transform (#578)

Replaces every line of IrreducibleLoops.scala. This reimplements the
algorithm in a way much closer to the paper. This new code does much
less explicit bookkeeping work. It replaces some old code that went
through the dfsp_pos with new code that does some kind of
topologically-ordered dynamic programming. In doing so, it is my hope
that it is more obviously correct.

Also:
- fixes certain bugs in the transform relating to topological order
- removes state machine
- adds mutability in data structures to make it closer to the paper
- fixes analysis and transform for nested irreducible loops

Closes https://github.com/UQ-PAC/BASIL/issues/410

add top to symvalues domain (#575)

Attempts to fix crashes seen in SVA when exprs evaluate to top in the
abstract domain and calling `toOffsets`, e.g. in cntlm-O3
`https://github.com/agle/basilbench/tree/main/cntlm-noduk`

`./mill run -i ../tvbins/cntlm-noduk/cntlm-noduk.gts --lifter --dump-il
cntlm --simplify --dsa= `

Just joins a `Constant -> top` to the symvalset domain if adding a top
constant, theoretically with split-globals it should probably also map
all the global bases to top since they could alias? Regardless the
assertion should be enough to justify keeping them separate.

---------

Co-authored-by: rina <k@rina.fyi>

 docs: use fixed -source-links format  (#585)

one has to wonder why the old form didn't throw an error

thanks to li haoyi in
https://www.github.com/com-lihaoyi/mill/issues/5454

fix recursion issue in IntervalDSA

test case that covers recursion issue

move recursion test so it won't break everything

fix flow sensitivity of offsetprop clobber (#560)

Bug found by translation validator in
`examples/cntlm-noduk/cntlm-noduk.gts`
`CopyProp-unicode_4269100-split-2`

nix-cc.sh: support custom compile flags and update docs (#580)

fixes https://github.com/UQ-PAC/BASIL/issues/534

Cleanup of CLI help messages and clarify dependencies between options.
Marked --analyse, --memory-regions  and BAP options as deprecated.
Make --dsa turn on --simplify automatically rather than giving an error.
API changes: renamed
   --summarise-procedures to --generate-procedure-summaries
   --parameter-form to --generate-parameters
for consistency with other --generate-* options, and
   --procedure-call-depth to --trim-depth
to emphasize its connection with --trim-early.

Added some examples to show different input options and output options.

Clarify the --dsa= default explanation.

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

Improve the explanation of no-irreducible-loops

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

Fix formatting

Fix --help problem, to ensure it is not sorted

Rename --no-irreducible-loops to --transform-irreducible-loops and make it independent of --generate-loop-invariants.  However, enabling --generate-loop-invariants automatically enables --transform-irreducible-loops.

Rename --memory-transform to --transform-memory
and also --generate-parameters (was --parameter-form) to --transform-parameters for consistency.

minor fmt changes

Fix LoopInvariantTests by turning on transform irreducible loops

simplify the --spec message because there are multiple ways of reading the symbol table

Minor help string corrections

Fix --transform-memory example

Revert double-negation confusion so that legacy .adt tests still transform irreducible loops.

Rename StaticAnalysisConfig irreducibleLoops field to removeIrreducibleLoops for clarity

Remove --spec requires --relf check, since the following check is clearer.

Clarify spec-requires-relf message

Turn on the --lifter flag for .gtirb inputs only, rather than giving an error.

fmt changes

Wpdual fix (#593)

Fixes a soundness issue in the wp dual domain causing it to sometimes
require False.

Run irreducible loops when function summaries are enabled (#597)

Since loop headers need to be known for widening, we need to run the
irreducible loop analysis if procedure summaries are generated.

Errors in documentation (#598)

Was reading the documentation for the IL / IR and saw this, I will
probably read a lot more of it over the coming week as I write some of
my reports so happy to keep this open.

Simplify (some) big concats (#599)

You may have seen expressions like the following (using boogie syntax):
```
bvor32(bvand32((((((((((((((((((((((((((((((((bvlshr32(#R19_1209[32:0], 31bv32)[1:0] ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]) ++ bvlshr32(#R19_1209[32:0], 31bv32)[1:0]), 4227858432bv32), bvand32(bvor32(bvand32(bvor32(bvlshr32(#R19_1209[32:0], 6bv32), bvshl32(#R19_1209[32:0], 26bv32)), 4294967295bv32), 0bv32), 67108863bv32))
```
This is taken from main in cntlm. If we look closely, this is just a
concatenation of the same singular bit over and over again! We could
just replace it with a repeat.
```
bvor32(bvand32(repeat32_1(bvlshr32(#R19_1209[32:0], 31bv32)[1:0]), 4227858432bv32), bvand32(bvor32(bvand32(bvor32(bvlshr32(#R19_1209[32:0], 6bv32), bvshl32(#R19_1209[32:0], 26bv32)), 4294967295bv32), 0bv32), 67108863bv32))
```
But if you think about it, a repeat of a one bit value is the same thing
as a sign extend.
```
bvor32(bvand32(sign_extend31_1(bvlshr32(#R19_1209[32:0], 31bv32)[1:0]), 4227858432bv32), bvand32(bvor32(bvand32(bvor32(bvlshr32(#R19_1209[32:0], 6bv32), bvshl32(#R19_1209[32:0], 26bv32)), 4294967295bv32), 0bv32), 67108863bv32))
```
But if you think about it even more, we're doing a logical right shift
by 31 then taking the first bit, and then sign extending... That's just
an arithmetic right shift!
```
bvor32(bvand32(bvashr32(#R19_1209[32:0], 31bv32), 4227858432bv32), bvand32(bvor32(bvand32(bvor32(bvlshr32(#R19_1209[32:0], 6bv32), bvshl32(#R19_1209[32:0], 26bv32)), 4294967295bv32), 0bv32), 67108863bv32))
```
I suspect that these big concat chain comes from somewhere in the
lifting pipeline not knowing how to handle 32 bit arithmetic shifts
nicely. Hopefully the simplification helps somewhere!

allow IR to be dumped in SimplifyPipeline without the unrelated --analyse flag being active

fmt

fmt again

ci: fix link checking by excluding files and replace link (#614)

it looks like both scaladoc and javadoc have invalid links in their css.
new lychee version enabled link checking inside css files.

add new mill modules to streamline using debugger

debugger documentation

fix test path

fix #601

fix OffsetProp specJoinState breaking state when run on same block twice

correctly check collect bounds in resolveGlobalOverlapping

adds Havoc to BASIL IR, fixes handling of __VERIFIER_nondet, some support for Havoc in analyses

fix GammaDomain & KnownBits for Havoc

Jesse interface thesis proj (#589)

Co-authored-by: Jesse Graf <grje@cit.tum.de>
Co-authored-by: am <a.michael1@uq.edu.au>
Co-authored-by: rina <k@rina.fyi>

Prevent entry blocks from having incoming jumps (#609)

Fixes #579, #605

The transform to do this already existed, it was just being performed
too early which meant it did not have the intended effect. Rearranging
the order fixes this issue.

I am wondering if `applyRpoTransform` should also be moved to still be
after `makeProcEntriesNonLoops`? I wasn't sure if that matters or not. I
don't think it should matter for the others?

---------

Co-authored-by: l-kent <l.kent@uq.edu.au>

fixes